apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nextjs-app
  description: nextjs-app created using self service flow
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: test
  lifecycle: experimental
